"""Convert between rapi Endpoint definitions and OpenAPI 3 YAML/JSON."""

from __future__ import annotations

import json
from typing import Any

from .models import Endpoint, ResponseSpec, Rule

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore


def _require_yaml() -> None:
    if yaml is None:  # pragma: no cover
        raise SystemExit(
            "OpenAPI format requires PyYAML. Install with: pip install pyyaml"
        )


def endpoints_to_openapi(endpoints: list[Endpoint], *, title: str = "rapi mocks", version: str = "1.0.0", include_extensions: bool = True) -> dict[str, Any]:
    """Build a minimal OpenAPI 3.0 document from rapi endpoints."""
    paths: dict[str, Any] = {}

    for ep in endpoints:
        path_item = paths.setdefault(ep.path, {})
        op: dict[str, Any] = {
            "operationId": ep.name.replace(":", "_").replace("/", "_"),
            "summary": f"Mock {ep.method} {ep.path}",
            "responses": {},
        }

        # parameters from query params validation
        params = []
        for key, expected in (ep.params or {}).items():
            p: dict[str, Any] = {
                "name": key,
                "in": "query",
                "required": True,
                "schema": {"type": "string"},
            }
            if expected is not None:
                p["description"] = f"rapi expected: {expected}"
                if not expected.startswith("~"):
                    p["schema"] = {"type": "string", "enum": [expected]}
            params.append(p)
        if params:
            op["parameters"] = params

        # default response
        status = str(ep.default.status)
        op["responses"][status] = _response_object(ep.default)

        # rule responses as additional status codes / extensions
        if ep.rules:
            x_rules = []
            for rule in ep.rules:
                st = str(rule.response.status)
                # keep first example per status if not present
                if st not in op["responses"]:
                    op["responses"][st] = _response_object(rule.response)
                x_rules.append({
                    "when": rule.conditions,
                    "status": rule.response.status,
                    "body": rule.response.body,
                    **({"content_type": rule.response.content_type} if rule.response.content_type else {}),
                })
            if include_extensions:
                op["x-rapi-rules"] = x_rules

        # rapi-only extensions (omit with include_extensions=False)
        if include_extensions:
            if ep.expected_body is not None:
                op["x-rapi-expected-body"] = ep.expected_body
            if ep.strict_params:
                op["x-rapi-strict-params"] = True
            if ep.list_key:
                op["x-rapi-list"] = {
                    "key": ep.list_key,
                    "item": ep.list_item,
                    "count": ep.list_count,
                    "start": ep.list_start,
                }
            if ep.default.content_type:
                op["x-rapi-content-type"] = ep.default.content_type

        path_item[ep.method.lower()] = op

    return {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
            "description": "Generated by rapi (REST API mock)",
        },
        "paths": paths,
    }


def _response_object(spec: ResponseSpec) -> dict[str, Any]:
    body = spec.body
    example: Any = body
    try:
        example = json.loads(body)
    except (json.JSONDecodeError, TypeError):
        pass

    ct = spec.content_type or (
        "application/json" if isinstance(example, (dict, list)) else "text/plain"
    )
    return {
        "description": f"HTTP {spec.status}",
        "content": {
            ct: {
                "example": example,
            }
        },
    }


def openapi_to_endpoints(doc: dict[str, Any]) -> list[dict[str, Any]]:
    """Convert OpenAPI document to list of endpoint dicts for DefinitionStore.import_from."""
    paths = doc.get("paths") or {}
    result: list[dict[str, Any]] = []

    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, op in path_item.items():
            if method.startswith("x-") or method in ("parameters", "summary", "description", "servers"):
                continue
            if not isinstance(op, dict):
                continue
            method_u = method.upper()
            if method_u not in {
                "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS", "QUERY", "TRACE"
            }:
                continue

            default_status = 200
            default_body = "OK"
            default_ct = None
            responses = op.get("responses") or {}

            # prefer 200, else first numeric status
            status_keys = sorted(
                responses.keys(),
                key=lambda s: (0 if str(s) == "200" else 1, str(s)),
            )
            for sk in status_keys:
                try:
                    code = int(str(sk))
                except ValueError:
                    continue
                default_status = code
                default_body, default_ct = _extract_example(responses[sk])
                break

            rules = []
            for raw in op.get("x-rapi-rules") or []:
                if not isinstance(raw, dict):
                    continue
                rules.append({
                    "when": raw.get("when") or {},
                    "status": int(raw.get("status", 400)),
                    "body": str(raw.get("body", "")),
                    **({"content_type": raw["content_type"]} if raw.get("content_type") else {}),
                })

            params: dict[str, str | None] = {}
            for p in op.get("parameters") or []:
                if not isinstance(p, dict) or p.get("in") != "query":
                    continue
                name = p.get("name")
                if not name:
                    continue
                desc = p.get("description") or ""
                if desc.startswith("rapi expected: "):
                    params[str(name)] = desc[len("rapi expected: "):]
                else:
                    schema = p.get("schema") or {}
                    enum = schema.get("enum")
                    if enum:
                        params[str(name)] = str(enum[0])
                    else:
                        params[str(name)] = None

            ep: dict[str, Any] = {
                "name": op.get("operationId") or f"{method_u}:{path}",
                "path": path,
                "method": method_u,
                "default": {
                    "status": default_status,
                    "body": default_body if isinstance(default_body, str) else json.dumps(default_body, ensure_ascii=False),
                    **({"content_type": default_ct} if default_ct else {}),
                },
                "rules": rules,
            }
            if params:
                ep["params"] = params
            if op.get("x-rapi-strict-params"):
                ep["strict_params"] = True
            if op.get("x-rapi-expected-body") is not None:
                ep["expected_body"] = op["x-rapi-expected-body"]
            if op.get("x-rapi-list"):
                lst = op["x-rapi-list"]
                ep["list_key"] = lst.get("key")
                ep["list_item"] = lst.get("item")
                ep["list_count"] = lst.get("count")
                ep["list_start"] = lst.get("start", 1)
            result.append(ep)

    return result


def _extract_example(resp_obj: Any) -> tuple[Any, str | None]:
    if not isinstance(resp_obj, dict):
        return "OK", None
    content = resp_obj.get("content") or {}
    if not content:
        return resp_obj.get("description") or "OK", None
    # prefer application/json
    if "application/json" in content:
        block = content["application/json"] or {}
        ex = block.get("example")
        if ex is None and block.get("examples"):
            first = next(iter(block["examples"].values()), {})
            ex = first.get("value") if isinstance(first, dict) else first
        if ex is None:
            return "{}", "application/json"
        return ex, "application/json"
    # any first content type
    ct = next(iter(content.keys()))
    block = content[ct] or {}
    ex = block.get("example", "OK")
    return ex, ct


def dump_openapi(endpoints: list[Endpoint], path: str, *, as_json: bool = False, include_extensions: bool = True) -> None:
    doc = endpoints_to_openapi(endpoints, include_extensions=include_extensions)
    from pathlib import Path
    p = Path(path)
    if as_json or p.suffix.lower() == ".json":
        p.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        return
    _require_yaml()
    p.write_text(
        yaml.dump(doc, allow_unicode=True, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def load_openapi(path: str) -> list[dict[str, Any]]:
    from pathlib import Path
    text = Path(path).read_text(encoding="utf-8")
    suffix = Path(path).suffix.lower()
    if suffix in (".yaml", ".yml"):
        _require_yaml()
        doc = yaml.safe_load(text)
    else:
        # try yaml first if available, else json
        doc = None
        if yaml is not None:
            try:
                doc = yaml.safe_load(text)
            except Exception:
                doc = None
        if doc is None:
            doc = json.loads(text)
    if not isinstance(doc, dict):
        raise SystemExit("OpenAPI document must be a mapping/object")
    return openapi_to_endpoints(doc)
