"""Convert between rapi Endpoint definitions and OpenAPI 3 YAML/JSON."""

from __future__ import annotations

import json
from typing import Any

from .models import Endpoint, ResponseSpec, Rule

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore


def _require_yaml() -> None:
    if yaml is None:  # pragma: no cover
        raise SystemExit(
            "OpenAPI format requires PyYAML. Install with: pip install pyyaml"
        )


def endpoints_to_openapi(endpoints: list[Endpoint], *, title: str = "rapi mocks", version: str = "1.0.0", include_extensions: bool = True) -> dict[str, Any]:
    """Build a minimal OpenAPI 3.0 document from rapi endpoints."""
    paths: dict[str, Any] = {}

    for ep in endpoints:
        path_item = paths.setdefault(ep.path, {})
        op: dict[str, Any] = {
            "operationId": ep.name.replace(":", "_").replace("/", "_"),
            "summary": f"Mock {ep.method} {ep.path}",
            "responses": {},
        }

        # parameters from query params validation
        params = []
        for key, expected in (ep.params or {}).items():
            p: dict[str, Any] = {
                "name": key,
                "in": "query",
                "required": True,
                "schema": {"type": "string"},
            }
            if expected is not None:
                p["description"] = f"rapi expected: {expected}"
                if not expected.startswith("~"):
                    p["schema"] = {"type": "string", "enum": [expected]}
            params.append(p)
        if params:
            op["parameters"] = params

        # default response
        status = str(ep.default.status)
        op["responses"][status] = _response_object(ep.default)

        # rule responses as additional status codes / extensions
        if ep.rules:
            x_rules = []
            for rule in ep.rules:
                st = str(rule.response.status)
                # keep first example per status if not present
                if st not in op["responses"]:
                    op["responses"][st] = _response_object(rule.response)
                x_rules.append({
                    "when": rule.conditions,
                    "status": rule.response.status,
                    "body": rule.response.body,
                    **({"content_type": rule.response.content_type} if rule.response.content_type else {}),
                })
            if include_extensions:
                op["x-rapi-rules"] = x_rules

        # rapi-only extensions (omit with include_extensions=False)
        if include_extensions:
            if ep.expected_body is not None:
                op["x-rapi-expected-body"] = ep.expected_body
            if ep.strict_params:
                op["x-rapi-strict-params"] = True
            if ep.list_key:
                xlist = {
                    "key": ep.list_key,
                    "item": ep.list_item,
                    "count": ep.list_count,
                    "start": ep.list_start,
                }
                if getattr(ep, "list_date_start", None):
                    xlist["date_start"] = ep.list_date_start
                if getattr(ep, "list_date_increment_type", None):
                    xlist["date_increment_type"] = ep.list_date_increment_type
                if int(getattr(ep, "list_date_increment_unit", 1) or 1) != 1:
                    xlist["date_increment_unit"] = int(ep.list_date_increment_unit)
                op["x-rapi-list"] = xlist
            if ep.default.content_type:
                op["x-rapi-content-type"] = ep.default.content_type

        path_item[ep.method.lower()] = op

    return {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
            "description": "Generated by rapi (REST API mock)",
        },
        "paths": paths,
    }


def _response_object(spec: ResponseSpec) -> dict[str, Any]:
    body = spec.body
    example: Any = body
    try:
        example = json.loads(body)
    except (json.JSONDecodeError, TypeError):
        pass

    ct = spec.content_type or (
        "application/json" if isinstance(example, (dict, list)) else "text/plain"
    )
    return {
        "description": f"HTTP {spec.status}",
        "content": {
            ct: {
                "example": example,
            }
        },
    }


def _resolve_ref(doc: dict[str, Any], obj: Any, _seen: set[str] | None = None) -> Any:
    """Resolve local $ref like #/components/schemas/Pet (shallow, cycle-safe)."""
    if not isinstance(obj, dict):
        return obj
    ref = obj.get("$ref")
    if not isinstance(ref, str) or not ref.startswith("#/"):
        return obj
    if _seen is None:
        _seen = set()
    if ref in _seen:
        return obj
    _seen.add(ref)
    cur: Any = doc
    for part in ref[2:].split("/"):
        part = part.replace("~1", "/").replace("~0", "~")
        if not isinstance(cur, dict) or part not in cur:
            return obj
        cur = cur[part]
    if isinstance(cur, dict) and "$ref" in cur:
        return _resolve_ref(doc, cur, _seen)
    return cur


def _merge_parameters(doc: dict[str, Any], path_item: dict[str, Any], op: dict[str, Any]) -> list[dict[str, Any]]:
    """Path-level + operation-level parameters (operation overrides same name+in)."""
    merged: dict[tuple[str, str], dict[str, Any]] = {}
    for src in (path_item.get("parameters") or [], op.get("parameters") or []):
        for p in src:
            if not isinstance(p, dict):
                continue
            p = _resolve_ref(doc, p)
            if not isinstance(p, dict):
                continue
            name = p.get("name")
            loc = p.get("in") or "query"
            if not name:
                continue
            merged[(str(name), str(loc))] = p
    return list(merged.values())


def _example_from_schema(schema: Any) -> Any:
    if not isinstance(schema, dict):
        return None
    if "example" in schema:
        return schema["example"]
    if "default" in schema:
        return schema["default"]
    # minimal synthetic example from type
    t = schema.get("type")
    if t == "object":
        props = schema.get("properties") or {}
        return {k: _example_from_schema(v) if isinstance(v, dict) else None for k, v in list(props.items())[:20]}
    if t == "array":
        item = _example_from_schema(schema.get("items") or {})
        return [item] if item is not None else []
    if t == "integer" or t == "number":
        return 0
    if t == "boolean":
        return False
    if t == "string":
        return schema.get("enum", ["string"])[0] if schema.get("enum") else "string"
    return None


def _extract_request_body_example(doc: dict[str, Any], op: dict[str, Any]) -> Any | None:
    rb = op.get("requestBody")
    if not isinstance(rb, dict):
        return None
    rb = _resolve_ref(doc, rb)
    if not isinstance(rb, dict):
        return None
    content = rb.get("content") or {}
    if not isinstance(content, dict) or not content:
        return None
    # prefer application/json
    blocks = []
    if "application/json" in content:
        blocks.append(content["application/json"])
    blocks.extend(content[k] for k in content if k != "application/json")
    for block in blocks:
        if not isinstance(block, dict):
            continue
        if "example" in block:
            return block["example"]
        if block.get("examples"):
            first = next(iter(block["examples"].values()), {})
            if isinstance(first, dict) and "value" in first:
                return first["value"]
            return first
        schema = block.get("schema")
        if schema is not None:
            schema = _resolve_ref(doc, schema)
            ex = _example_from_schema(schema)
            if ex is not None:
                return ex
    return None


def openapi_to_endpoints(doc: dict[str, Any]) -> list[dict[str, Any]]:
    """Convert OpenAPI document to list of endpoint dicts for DefinitionStore.import_from."""
    paths = doc.get("paths") or {}
    result: list[dict[str, Any]] = []

    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, op in path_item.items():
            if method.startswith("x-") or method in ("parameters", "summary", "description", "servers"):
                continue
            if not isinstance(op, dict):
                continue
            method_u = method.upper()
            if method_u not in {
                "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS", "QUERY", "TRACE"
            }:
                continue

            default_status = 200
            default_body = "OK"
            default_ct = None
            responses = op.get("responses") or {}

            # Collect numeric response statuses with examples
            numeric_responses: list[tuple[int, str, Any, str | None]] = []
            for sk, resp in responses.items():
                try:
                    code = int(str(sk))
                except ValueError:
                    continue
                body, ct = _extract_example(doc, resp)
                body_s = body if isinstance(body, str) else json.dumps(body, ensure_ascii=False)
                numeric_responses.append((code, str(sk), body_s, ct))

            # prefer 200, else first by status code
            numeric_responses.sort(key=lambda x: (0 if x[0] == 200 else 1, x[0]))
            if numeric_responses:
                default_status, _, default_body, default_ct = numeric_responses[0]

            rules = []
            # Explicit x-rapi-rules first (higher priority: first-match wins)
            for raw in op.get("x-rapi-rules") or []:
                if not isinstance(raw, dict):
                    continue
                rules.append({
                    "when": raw.get("when") or {},
                    "status": int(raw.get("status", 400)),
                    "body": str(raw.get("body", "")),
                    **({"content_type": raw["content_type"]} if raw.get("content_type") else {}),
                })

            # Auto rules: other statuses → query.force=<status>
            # (OpenAPI has no "when"; rapi convention for trying error examples)
            for code, _sk, body_s, ct in numeric_responses:
                if code == default_status:
                    continue
                rule: dict[str, Any] = {
                    "when": {"query.force": str(code)},
                    "status": code,
                    "body": body_s,
                }
                if ct:
                    rule["content_type"] = ct
                rules.append(rule)

            params: dict[str, str | None] = {}
            for p in _merge_parameters(doc, path_item, op):
                if p.get("in") != "query":
                    continue
                name = p.get("name")
                if not name:
                    continue
                # Import all query parameters as rapi required checks (mock-friendly).
                # Optional OpenAPI query params still become "must be present" for mocks;
                # skip only when explicitly x-rapi-ignore.
                if p.get("x-rapi-ignore"):
                    continue
                desc = p.get("description") or ""
                if desc.startswith("rapi expected: "):
                    params[str(name)] = desc[len("rapi expected: "):]
                else:
                    schema = p.get("schema") or {}
                    schema = _resolve_ref(doc, schema) if isinstance(schema, dict) else schema
                    if isinstance(schema, dict):
                        enum = schema.get("enum")
                        if enum:
                            params[str(name)] = str(enum[0])
                        else:
                            params[str(name)] = None
                    else:
                        params[str(name)] = None

            ep: dict[str, Any] = {
                "name": op.get("operationId") or f"{method_u}:{path}",
                "path": path,
                "method": method_u,
                "default": {
                    "status": default_status,
                    "body": default_body if isinstance(default_body, str) else json.dumps(default_body, ensure_ascii=False),
                    **({"content_type": default_ct} if default_ct else {}),
                },
                "rules": rules,
            }
            if params:
                ep["params"] = params
            if op.get("x-rapi-strict-params"):
                ep["strict_params"] = True
            if op.get("x-rapi-expected-body") is not None:
                ep["expected_body"] = op["x-rapi-expected-body"]
            else:
                # From standard OpenAPI requestBody example (not as strict validation by default)
                # Store only when requestBody.required so mock can optional-validate
                rb = op.get("requestBody")
                if isinstance(rb, dict):
                    rb_res = _resolve_ref(doc, rb)
                    if isinstance(rb_res, dict) and rb_res.get("required"):
                        ex = _extract_request_body_example(doc, op)
                        if ex is not None:
                            ep["expected_body"] = (
                                ex if isinstance(ex, str) else json.dumps(ex, ensure_ascii=False)
                            )
            if op.get("x-rapi-list"):
                lst = op["x-rapi-list"]
                ep["list_key"] = lst.get("key")
                ep["list_item"] = lst.get("item")
                ep["list_count"] = lst.get("count")
                ep["list_start"] = lst.get("start", 1)
                if lst.get("date_start"):
                    ep["list_date_start"] = lst.get("date_start")
                if lst.get("date_increment_type"):
                    ep["list_date_increment_type"] = lst.get("date_increment_type")
                if lst.get("date_increment_unit") is not None:
                    ep["list_date_increment_unit"] = int(lst.get("date_increment_unit") or 1)
            result.append(ep)

    return result


def _extract_example(doc: dict[str, Any], resp_obj: Any) -> tuple[Any, str | None]:
    if not isinstance(resp_obj, dict):
        return "OK", None
    resp_obj = _resolve_ref(doc, resp_obj)
    if not isinstance(resp_obj, dict):
        return "OK", None
    content = resp_obj.get("content") or {}
    if not content:
        return resp_obj.get("description") or "OK", None
    # prefer application/json
    if "application/json" in content:
        block = content["application/json"] or {}
        ex = block.get("example")
        if ex is None and block.get("examples"):
            first = next(iter(block["examples"].values()), {})
            first = _resolve_ref(doc, first) if isinstance(first, dict) else first
            ex = first.get("value") if isinstance(first, dict) else first
        if ex is None and block.get("schema"):
            schema = _resolve_ref(doc, block["schema"])
            ex = _example_from_schema(schema)
        if ex is None:
            return "{}", "application/json"
        return ex, "application/json"
    # any first content type
    ct = next(iter(content.keys()))
    block = content[ct] or {}
    if not isinstance(block, dict):
        return "OK", ct
    ex = block.get("example")
    if ex is None and block.get("schema"):
        schema = _resolve_ref(doc, block["schema"])
        ex = _example_from_schema(schema)
    if ex is None:
        ex = "OK"
    return ex, ct


def dump_openapi(endpoints: list[Endpoint], path: str, *, as_json: bool = False, include_extensions: bool = True) -> None:
    doc = endpoints_to_openapi(endpoints, include_extensions=include_extensions)
    from pathlib import Path
    p = Path(path)
    if as_json or p.suffix.lower() == ".json":
        p.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        return
    _require_yaml()
    p.write_text(
        yaml.dump(doc, allow_unicode=True, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def load_openapi(path: str) -> list[dict[str, Any]]:
    from pathlib import Path
    text = Path(path).read_text(encoding="utf-8")
    suffix = Path(path).suffix.lower()
    if suffix in (".yaml", ".yml"):
        _require_yaml()
        doc = yaml.safe_load(text)
    else:
        # try yaml first if available, else json
        doc = None
        if yaml is not None:
            try:
                doc = yaml.safe_load(text)
            except Exception:
                doc = None
        if doc is None:
            doc = json.loads(text)
    if not isinstance(doc, dict):
        raise SystemExit("OpenAPI document must be a mapping/object")
    return openapi_to_endpoints(doc)
